language: python
python:
      - '3.8'

addons:
  chrome: stable
  firefox: stable

before_script:
      - pip install -r requirements.txt

branches:
    only:
        - staging

env: DJANGO_SETTINGS_MODULE="app_purbeurre.settings.travis"

services:
      - postgresql

script:
      - python manage.py test