language: python
python:
      - '3.8'

before_script:
      - pip install -r requirements.txt

branches:
    only:
        - staging

env: DJANGO_SETTINGS_MODULE="app_purbeurre.settings.travis"

services:
      - postgresql

script:
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py test