dist: bionic
language: python

python:
      - '3.8'

addons:
  chrome: stable
  firefox: latest

before_script:
      - install-webdrivers

branches:
    only:
        - staging

env: DJANGO_SETTINGS_MODULE="app_purbeurre.settings.travis"

services:
      - postgresql

script:
      - python manage.py test tests.test_chrome