language: python
python:
      - '3.8'

addons:
  chrome: stable
  firefox: latest

before_script:
      - wget "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz"
      - tar xfz geckodriver-v0.24.0-linux64.tar.gz
      - sudo mv geckodriver /usr/local/bin
      - 'export DISPLAY=:99.0'
      - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - sleep 3
      - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
      - export CHROME_BIN=chromium-browser
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 

branches:
    only:
        - staging

env: DJANGO_SETTINGS_MODULE="app_purbeurre.settings.travis"

services:
      - postgresql

script:
      - python manage.py test